version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      NYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./migrations/base.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    # Uncomment to expose the port to the host machine
    # ports:
    #   - ${DB_PORT}:${DB_PORT}

  redis:
    image: bitnami/redis:latest
    user: root
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASS}
    # Uncomment to expose the port to the host machine
    # ports:
    #   - ${REDIS_PORT}:${REDIS_PORT}

  bancho:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    tty: true
    env_file:
      - .env
    volumes:
      - .data:/home/bpyuser/.data

  nginx:
    build:
      context: ./docker/nginx-with-geoip2
      args:
        - ENABLED_MODULES=geoip2
    image: nginx-with-geoip2
    depends_on:
      - bancho
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./docker/nginx-with-geoip2/main.conf:/etc/nginx/nginx.conf:ro
      - data:/.data:ro
      - ${SSL_CERT_PATH}:/etc/ssl/certs/bancho.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/bancho.key:ro
      # Uncomment if you have downloaded the database from maxmind
      #- ${MMD_DB_PATH}:/etc/GeoLite2-City.mmdb:ro
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${HOST_PORT}:${HOST_PORT}
